### ISSUE TITLE
Routing loop

### ISSUE THREAD

**Issue by hosley** [hosley/checkin#10]
- [x] room ID page ▶️ list of students ▶️ confirmation page ▶️ room ID page (for Driver/Therapist/Teacher from specific rooms)

- [x] teacher dashboard page ▶️ list of students ▶️ confirmation page ▶️ teacher dashboard page (for Teacher from specific rooms)

**Comment by jaswinne** [comment]
checking in code, put titles in the title bar i.e. Check In: {room}

**Comment by hosley** [comment]
@jaswinne if everything is done please close the issue. If not please comment what is left.

**Comment by jaswinne** [comment]
just wanting testing outside of myself. I believe it to be done
