### ISSUE TITLE
Classroom dropdown aesthetics

### ISSUE THREAD

**Issue by ChrisRogersT** [hosley/checkin#14]
In the login page, the classroom selection item should be made a button to be consistent with the other options (admin, therapy, kitchen).

**Comment by jaswinne** [comment]
+1

**Comment by ChrisRogersT** [comment]
I have updated the classroom selection to be a button like the other room types. Currently the selection involves each room being a button, but I can see this getting ugly if we have more than a handful of rooms. I believe changing the rooms to radio inputs will make it more attractive and shouldn't be hard to implement should the need arise.

**Comment by hosley** [comment]
what about a button that takes you to a list of rooms (like we currently do with students) where if a row is clicked it logs you into the room?

**Comment by ChrisRogersT** [comment]
I'm not against it.
