### ISSUE TITLE
Checked students persist through "back"

### ISSUE THREAD

**Issue by ChrisRogersT** [hosley/checkin#17]
Certainly on the checkin tab, but probably on the other checkin/out tabs:
When a student is selected for checkin, but the user changes tabs or presses the back button instead of clicking the checkin button, the selected students remains visually checked when the user returns to the original tab. However, even though the student's button indicates they are checked in, the background logic treats them as not checked in and causes a few strange behaviors. 

To recreate this bug:

1. go to the checkin tab
2. enter a valid user id
3. select a student by pressing the checkin button
4. press the back button to return to the user id prompt
5. enter a valid user id
6. the student should still visibly be selected

**Comment by ChrisRogersT** [comment]
One idea to potentially pursue, which might aid with other issues, would be to in some way destroy the tab upon view change and then recreate it. This may not be the ideal solution with regard to the back button.

**Comment by hosley** [comment]
This should be fixed by d7694024b21c2a520b7ee9f623c20a53abef7b09
