### ISSUE TITLE
Therapist page

### ISSUE THREAD

**Issue by ChrisRogersT** [hosley/checkin#28]
# wants:
- [ ] outpatient tracking
- [x] therapy handoff

**Comment by ChrisRogersT** [comment]
also look at #41

**Comment by jaswinne** [comment]
checkout and checkin therapist must match... up for discussion

**Comment by jaswinne** [comment]
Something something TBD lockout if unchecked back in. shame those thrapists for not doing their jobs

**Comment by jaswinne** [comment]
classroom for outpatient?? maybe a checkbox for outpatient on creation

**Comment by ChrisRogersT** [comment]
Small bug, When a student is checked to a therapist, and then they are checked out on the classroom page, it will do the appropriate checkout, but also log a "checkin by therapist" as if the therapist was returning them to the room immediately after they were logged as being "checked out" of the room by the check-out tab.
