### ISSUE TITLE
Therapist check in/out time set

### ISSUE THREAD

**Issue by ChrisRogersT** [hosley/checkin#31]
**Problem**
Some degree of freedom is requested on the timing of therapist check in/out.
It has been mentioned that some therapist's log all of their student times at the end of the day. This is somewhat at odds with the nature of the location tracking.

**Initial thoughts:**
Perhaps allow time marking upon student return to class

**Comment by jaswinne** [comment]
woah oh we're halfway there. reading and writing with the service works, all thats left is gettin dat data from the user via UI

**Comment by jaswinne** [comment]
bad modal look but theoretically functional
