### ISSUE TITLE
Database Tables

### ISSUE THREAD

**Issue by hosley** [hosley/checkin#4]
- [ ] Student Table: ID, Name
- [ ] Driver Table: ID, Name, Phone
- [ ] Teacher Table: ID, Name
- [ ] Present Student Table:  studentID, checkIn, checkOut
- [ ] Nap Table: studentID, napStart, napEnd
- [ ] Therapy Table: studentID, therapyStart, therapyEnd, therapyType

**Comment by ChrisRogersT** [comment]
Current db schema:

- students: _id, fName, lName, location, note, icon
  - note and icon are optional as of now
- users: _id, fName, lName, phone, role
  - role is used for privilege checking
- classrooms: roomNumber, students 
  - students is an array of strings where each entry is a student id for a child belonging to that classroom
- transactions: date, students

**Comment by jaswinne** [comment]
students in transactions are students: [
{
  id: '###'
  events: [
    time: 4:20,
    type: 'nurse checked out',
    by_id: '###'
  ]
}
]
