### ISSUE TITLE
Style/Functionality that needs to be fixed

### ISSUE THREAD

**Issue by hosley** [hosley/checkin#49]
## General
- [x] if portrait view is used classroom-id card needs to be vertically shrunk
- [x] classroom id input center

## Classroom
- [x] background color to the sand color
- [x] take ion-item out of list
- [x] signin signout nap need to have scroll content for cards and a static button location
- [x] making student details into cards
- [x] change generic ionicon
- [x] remove border-bottom from nap page (nap buttons)
- [x] rename nap buttons to nap slider
- [x] get roster student count text to baseline
- [x] reformat null list case to have bigger text
- [x] admin messing around in therapy causes issues
- [x] therapist button toggles before modal closes
- [ ] transaction times should reflect changes in therapy start time (might not happen)

## Therapist
- [x] background color to the sand color
- [x] therapist student details to card when not null case
- [x] fix padding on modal (add right padding?)
- [x] sort therapy transactions by start time, not real time
- [x] reformat null list case to match classroom (with bigger text as well) possibly raise vertical height
- [x] white line atop therapist student details for ipad view
- [x] move add to favorite to a card design/redesign with many classrooms in mind
- [x] modal => close app edge case
- [ ] clicking on old transactions to make them editable?

## Admin
- [x] reorder tabs 
- [x] background color
- [x] admin classroom to card list
- [x] faster run search bar
- [x] modal to page
- [x] button reformatting across all pages

## Kitchen 
- [ ] add key to bottom right
- [ ] card reformatting

**Comment by jaswinne** [comment]
transaction times will not change after the modal. no way

**Comment by hosley** [comment]
transaction times should reflect changes in therapy start time will not be implemented before soft launch, clicking on old transactions to make them editable will not happen anywhere but possibly admin. Kitchen stuff will be addressed in different issue
