### ISSUE TITLE
DB Hosting

### ISSUE THREAD

**Issue by hosley** [hosley/checkin#5]
- [x] Find where to host mySQL DB
- [x] set up mySQL

**Comment by ChrisRogersT** [comment]
Backand might auto setup and host TBD

**Comment by ChrisRogersT** [comment]
Did some initial testing and it seems that Backand can setup its own mysql db

**Comment by jaswinne** [comment]
👌👌👌

**Comment by ChrisRogersT** [comment]
As of now it appears cloudant will be the preferred host. To be tested
