### ISSUE TITLE
Second pass through of user roles and permissions

### ISSUE THREAD

**Issue by ChrisRogersT** [hosley/checkin#50]
We need to revise what roles are allowed to do what, and update classroom-id accordingly

**Comment by hosley** [comment]
In this commit 4f81e5465937eb3d70851fa6a448b7439ec0c205 I have locked admin out of therapy/therapist to avoid any unforseen issues

**Comment by ChrisRogersT** [comment]
- [ ] Add an encrypted password layer to the admin login

**Comment by jaswinne** [comment]
Admin -> all but therapy, therapist
!driver -> all but therapy, therapist, admin
driver -> checkin, signout
therapist -> all but admin

finished, closing and opening new issue with adding password to admin

**Comment by jaswinne** [comment]
#54
