### ISSUE TITLE
Admin reporting page tbds

### ISSUE THREAD

**Issue by ChrisRogersT** [hosley/checkin#57]
- [x] Change week/ get that week's data
- - [x] Make time in editable
- [x] Edit values on details page which persist to regular page
- [x] Warnings on headers
- [ ] Align columns
- [ ] Export to excel/ as a csv

- [x] make loader async
- [x] show loading spinner or something after button press until promise returns

**Comment by ChrisRogersT** [comment]
change week and edit values should be done from commits d0d8aaf8aca885cd26f9991c4324c6738f3a2b9f and 1c31cdfa60682659f063abb7fd7d239451a2b6ae respectively

**Comment by ChrisRogersT** [comment]
I un-marked export to excel/ as a csv because we need to go back and make it export the proper staff and client, this is somewhat contingent on interacting with Brian. But I am un-marking it so that we don't forget.

**Comment by hosley** [comment]
this has been moved to #70
