### ISSUE TITLE
Students who are left checked in over night are left in limbo

### ISSUE THREAD

**Issue by ChrisRogersT** [hosley/checkin#59]
Students who are checked in over night still have their location as present, but their transaction history for the day is empty.

We will need to add some kind of service that checks everyone out at some point.

I believe bryan said everyone should be checked out by 3, but I'm not sure how this interacts with late pickups. My main questions are:
- Do all the parents/drivers checkout the kids before 3 for sure?
- Is there a queue and sometimes people are checked out at 3:05 simply because it took 5 minutes to get through all the checkout?
- Should a teacher be responsible for checking out all "late-pickup" students who then get moved to after school care (and we have a fail safe for if the teacher forgets and we check that student out at some arbitrary but late time where their billing will be flagged and retroactively changed)?

**Comment by jaswinne** [comment]
the third bullet is what they said about transferring to ASC

**Comment by jaswinne** [comment]
can they be billed past three? have a check in the check out function that if in limbo, do the limbo fix  instead

**Comment by jaswinne** [comment]
if you checkout and they are in limbo, it doesn't add a checkout transaction, but does set their location to checked out
