### ISSUE TITLE
Backand Research

### ISSUE THREAD

**Issue by hosley** [hosley/checkin#6]
- [ ] research backand
- [ ] database to frontend hookups

http://blog.ionic.io/creating-an-ionic-app-with-mysql-and-backand/

**Comment by ChrisRogersT** [comment]
- [ ] make a backand account

**Comment by hosley** [comment]
If Chris prefers SQLlite/MySQL this can be closed

**Comment by ChrisRogersT** [comment]
Closing for now since we are considering other alternatives
