### ISSUE TITLE
Add authentication db and backend to support admin passwords

### ISSUE THREAD

**Issue by ChrisRogersT** [hosley/checkin#60]
- [x] Add authentication db
- [x] Add password checking on admin signin
- [x] Add password field to new admin creation
- [x] Add ability to change password
- [x] Add ability to reset password

**Comment by jaswinne** [comment]
no front end, but functions exist

**Comment by jaswinne** [comment]
i dont know where to leave this comment, but when editing a user it shows incorrect error messages
![image](https://cloud.githubusercontent.com/assets/5074948/23564712/9fad0082-0010-11e7-899c-7fb5d01fcc52.png)

**Comment by jaswinne** [comment]
also need to not be able to delete one's self as an admin probably

**Comment by jaswinne** [comment]
need 40 char requirement for both creating and changing password question
