### ISSUE TITLE
Live updating issues

### ISSUE THREAD

**Issue by ChrisRogersT** [hosley/checkin#68]
# Issue
On the internet browsers the app does not properly live update from a pouchdb instance on one browser to couchdb to a different pouchdb instance. 

# Details
- It isn't currently known exactly where the issue started but it seemed to work as intended some time ago.
- The ipad, which was last updated on Tuesday 2/28/17 in the morning, was able to push changes from its pouchdb instance to the couchdb instance. It was also able to pull changes made "manually" to the couchdb
- There have been intermittent connections where a web browser was able to get changes that had been "manually" made to the couchdb, but it can't be reliably recreated.

# Questions to investigate
- Is the ipad working because of some difference between it running as a mobile app whereas the computers are running in a web browser.
- Is chrome not working because of some update to the code we have made since 2/28/17
- Is there some sort of caching issue at play with regard to a regular window vs an incognito window
- Are other web browsers having any issues

**Comment by ChrisRogersT** [comment]
@njwhites2012 you said that in some way you were able to see changes made via the ipad on the desktop or vice versa, could you clarify that for me

**Comment by ChrisRogersT** [comment]
- After some minor testing I was able to see changes propogate from a firefox instance to the chrome instance and an edge instance. this took around 35 seconds to perform which could be part of why it seemed to not update properly

**Comment by ChrisRogersT** [comment]
I'm gonna lower us from defcon 3 to defcon 4 because it does seem like this is still working it just takes some time. But potentially an acceptable amount of time, on the order of 30 seconds. We should consider looking into where the app might be running slowly. I have been seeing some "[Violation] long running javascript task" in my console

**Comment by ChrisRogersT** [comment]
https://pouchdb.com/errors.html#replicating_attachments_slow

not sure that this is our issue but leaving this here for later

**Comment by ChrisRogersT** [comment]
more links for remembering 
https://www.youtube.com/watch?v=MALKo1bSa4Y
https://www.bennadel.com/blog/3212-syncing-local-pouchdb-data-with-remote-ibm-cloudant-database-in-angular-2-4-1.htm
https://docs.cloudant.com/replication_guide.html#filtered-replication

**Comment by ChrisRogersT** [comment]
I did some testing with a local db and it seems to confirm the suspicion that the issue isn't necessarily our code but more with the connection to the cloudant server. I'm going to watch that youtube link and see if I gain any insight from that, and if not email the cloudant support to see if they have any input. I'm also going to do a little testing from home because I feel that the work internet could possibly be limiting it in some way, although that would be a stretch.

**Comment by hosley** [comment]
@ChrisRogersT look here https://github.com/pouchdb/pouchdb/issues/6189 and this https://github.com/pouchdb/pouchdb/issues/5675

**Comment by ChrisRogersT** [comment]
Under the belief that the issue we have been having was caused by having too many live connections; I have updated auth provider and constants provider so that they don't have a local database and rather just use pouch as an interface to the remote couchdb. This seems to fix the issue so I am closing this issue.
